---
- name: Verify pod {{ pod_name }} is running
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ pod_namespace | default('default') }}"
    name: "{{ pod_name }}"
    wait: true
    wait_timeout: 300
    wait_condition:
      type: Ready
      status: "True"
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ k8s_context }}"
  register: verify_pod
