---
- name: Render ovn-kubernetes manifests
  command:
    chdir: "{{ project_dir }}/dist/images"
    cmd: |
      ./daemonset.sh --image={{ ovn_image }}
        --net-cidr=10.244.0.0/16 --svc-cidr=10.96.0.0/16
        --gateway-mode="shared" --disable-snat-multiple-gws
        --k8s-apiserver=https://{{ project }}-control-plane:6443
- name: Deploy ovn-kubernetes basic objects (Namespace, ConfigMap, ...etc.)
  k8s:
    src: "{{ project_dir }}/dist/yaml/ovn-setup.yaml"
    state: present
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ k8s_context }}"
- name: Deploy ovs-node Daemonset
  include_tasks: deploy-objects.yaml
  vars:
    deployment_object: ovs-node
# TODO Uncomment when issue of hw-offloaded to service is fixed
#- name: Enalbe hardware offload
#  include: enable-hardware-offload.yaml
- name: Deploy ovn-kubernetes components
  include_tasks: deploy-objects.yaml
  loop: "{{ ovn_k8s_deployments[2:] }}"
  loop_control:
    loop_var: deployment_object
- name: Copy ovn-kubernetes deployment files to artifacts
  copy:
    src: "{{ project_dir }}/dist/yaml/{{ item }}.yaml"
    dest: "{{ artifacts }}/{{ item }}.yaml"
  loop: "{{ ovn_k8s_deployments }}"
- name: Remove temp rendering dir
  file:
    path: "{{ project_dir }}"
    state: absent
