---
- name: Clean the vf-switcher service
  include: "stop_vf_switcher.yml"
  ignore_errors: yes

- name: Destroy Kind cluster
  command:
    cmd: sudo kind delete cluster --name {{ project }}

- include_role:
    name: projects-common/get-mlx-interfaces
- include_role:
    name: projects-common/clear-vfs
  loop: "{{ pfs }}"
  loop_control:
    loop_var: pf

