---
- name: Check project role exists
  stat:
    path: "{{ playbook_dir }}/roles/projects/{{ project }}"
  register: project_stat
- block:
    - debug:
        msg: Ending pahse. projects/{{ project }} not found (not implemented)
    - meta: end_play
  when: not project_stat.stat.exists
