---
- name: Deploy {{ deployment_object }}
  k8s:
    src: "{{ project_dir.path }}/dist/yaml/{{ deployment_object }}.yaml"
    state: present
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ k8s_context }}"
- name: Get {{ deployment_object }} pods list
  k8s_info:
    kind: Pod
    label_selectors:
      - name = {{ deployment_object }}
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ k8s_context }}"
  register: deployment_pods
- name: Verify {{ deployment_object }} pods are running
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: ovn-kubernetes
    name: "{{ item.metadata.name }}"
    wait: true
    wait_timeout: 300
    wait_condition:
      type: Ready
      status: "True"
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ k8s_context }}"
  loop: "{{ deployment_pods.resources }}"
