---
- name: Create ovn-kubernetes pod {{ pod_name }}
  k8s:
    state: present
    wait: true
    wait_timeout: 300
    wait_condition:
      type: Ready
      status: "True"
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ k8s_context }}"
    resource_definition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: "{{ pod_name }}"
        namespace: default
        annotations:
          k8s.ovn.org/pod-networks: |
            {"default":{"ip_addresses":["192.168.0.8/24"],
            "mac_address":"0a:58:c0:a8:00:08",
            "gateway_ips":["192.168.0.1"],"ip_address":"192.168.0.8/24",
            "gateway_ip":"192.168.0.1"}}
        labels:
          app: ovn-kubernetes
      spec:
        containers:
          - name: "{{ pod_name }}"
            image: "{{ pod_image }}"
            command: ["/bin/sh", "-c", "sleep infinity"]
- name: Get pod {{ pod_name }}
  k8s_info:
    api_version: v1
    kind: Pod
    namespace: default
    name: "{{ pod_name }}"
    wait: true
    wait_timeout: 300
    wait_condition:
      type: Ready
      status: "True"
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ k8s_context }}"
  register: test_pod
- name: Read pod ip and ovn-kubernetes annotations ip
  set_fact:
    pod_ip: "{{ test_pod.resources[0].status.podIP }}"
    pod_ovn_annotation: "{{ test_pod.resources[0].metadata.annotations['k8s.ovn.org/pod-networks'] | from_json }}"
- name: Verify pod ip is from ovn-kubernetes
  assert:
    success_msg: ovn-kubernetes test pod created successfully
    fail_msg: Failed to create ovn-kubernetes
    that:
      - "pod_ip in pod_ovn_annotation.default.ip_address"
- set_fact:
    pod_ips: "{{ pod_ips + [pod_ip] }}"
