---
- block:
    - name: Get kind nodes
      command:
        cmd: kind get nodes --name {{ project }}
      register: kind_nodes
    - name: Delete kube-proxy
      k8s:
        api_version: apps/v1
        kind: DaemonSet
        namespace: kube-system
        name: kube-proxy
        state: absent
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ k8s_context }}"
    - name: Clean kube-proxy iptables
      command:
        cmd: docker exec {{ item[0] }} {{ item[1] }}
      with_nested:
        - "{{ kind_nodes.stdout_lines }}"
        - ["iptables -F KUBE-SERVICES", "iptables -F KUBE-SERVICES -t nat"]
    - name: Disable IPv6
      command:
        cmd: docker exec {{ item[0] }} {{ item[1] }}
      with_nested:
        - "{{ kind_nodes.stdout_lines }}"
        - ["sysctl net.ipv6.conf.all.disable_ipv6=0", "sysctl net.ipv6.conf.all.forwarding=1"]
- name: Render ovn-kubernetes manifests
  command:
    chdir: "{{ project_dir.path }}/dist/images"
    cmd: |
      ./daemonset.sh --image={{ ovn_image }}
        --net-cidr=10.244.0.0/16 --svc-cidr=10.96.0.0/16
        --gateway-mode="shared" --disable-snat-multiple-gws
        --k8s-apiserver=https://{{ project }}-control-plane:6443
- name: Deploy ovn-kubernetes basic objects (Namespace, ConfigMap, ...etc.)
  k8s:
    src: "{{ project_dir.path }}/dist/yaml/ovn-setup.yaml"
    state: present
    kubeconfig: "{{ kubeconfig }}"
    context: "{{ k8s_context }}"
- name: Deploy ovn-kubernetes components
  include_tasks: deploy-objects.yaml
  loop: "{{ ovn_k8s_deployments[1:] }}"
  loop_control:
    loop_var: deployment_object
- name: Copy ovn-kubernetes deployment files to artifacts
  copy:
    src: "{{ project_dir.path }}/dist/yaml/{{ item }}.yaml"
    dest: "{{ artifacts }}/{{ item }}.yaml"
  loop: "{{ ovn_k8s_deployments }}"
- name: Remove temp rendering dir
  file:
    path: "{{ project_dir.path }}"
    state: absent
