---
- include_tasks: deploy-test-pods.yaml
  loop: "{{ pods_names }}"
  loop_control:
    loop_var: pod_name
- name: Send traffic between pods
  block:
    - k8s_exec:
        namespace: default
        pod: "{{ pod1_name }}"
        command: ping {{ pod_ips[1] }} -c 1
        kubeconfig: "{{ kubeconfig }}"
        context: "{{ k8s_context }}"
      register: traffic_result
    - assert:
        success_msg: Traffic between pods sent successfully
        fail_msg: Failed to send traffic between pods
        that:
          - "traffic_result.return_code == 0"
