---
- name: Check project files exists
  stat:
    path: projects/{{ project }}
  register: project_stat
- block:
    - debug:
        msg: Ending pahse. projects/{{ project }} not found (not implemented)
    - meta: end_play
  when: not project_stat.stat.exists
