---
- name: Deploy {{ project }} project
  hosts: kind_nodes
  become: true
  remote_user: root
  roles:
    - projects-common/assert-project-role
  tasks:
    - name: Read {{ project }} vars
      include_vars: roles/projects/{{ project }}/vars.yml
    - name: Deploy {{ project }}
      include_role:
        name: projects/{{ project }}/deploy
