---
- name: Test {{ project }} project
  hosts: kind_nodes
  collections:
    - community.kubernetes
  roles:
    - projects-common/assert-project-role
  tasks:
    - name: Read {{ project }} vars
      include_vars: roles/projects/{{ project }}/vars.yml
    - name: Test {{ project }}
      include_role:
        name: projects/{{ project }}/test
