---
- name: Undeploy ovn-kubernetes project
  hosts: kind_nodes
  become: true
  remote_user: root
  roles:
    - projects-common/assert-project-role
  tasks:
    - name: Read {{ project }} vars
      include_vars: projects/{{ project }}/vars.yaml
    - include_tasks: projects/{{ project }}/tasks/undeploy.yaml
