project: "{{ lookup('env', 'PROJECT') }}"
workspace: "{{ lookup('env', 'WORKSPACE') }}"
artifacts: "{{ workspace+ '/artifacts' }}"
num_worker: "{{ lookup('env', 'KIND_NUM_WORKER') }}"
pf_per_worker: 0
kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
kind_config: "{{ lookup('env', 'KIND_CONFIG') }}"
k8s_context: "kind-{{ project }}"
pull_request: "{{ lookup('env', 'PULL_REQUEST') }}"
unsupported_interfaces_list: [ "0x4115", "0x1015" ]
pod_subnet: "{{ lookup('env', 'POD_CIDER') }}"
service_subnet: "{{ lookup('env', 'SERVICE_CIDER') }}"
interfaces_type: "{{ lookup('env', 'INTERFACES_TYPE') }}"
num_vfs: "{{ lookup('env', 'NUM_VFS') }}"

