---
- name: Get mellanox intefaces
  include: "{{ playbook_dir }}/projects/tasks/get_mlx_interfaces.yml"

- name: Get worker nodes
  include: "{{ playbook_dir }}/projects/tasks/register_kind_nodes.yml"

- name: Render vf-switcher config
  block:
    - name: create temporary directory to render vf-switcher configuration
      tempfile:
        state: directory
        suffix: build
      register: vf_switcher_conf_temp_dir
    - set_fact:
        vf_switcher_rendered_config: "{{ vf_switcher_conf_temp_dir.path }}/vf-switcher.yaml"
    - name: Render vf-switcher configuration
      template:
        src: vf-switcher.yaml.j2
        dest: "{{ vf_switcher_rendered_config }}"
    - set_fact:
        deploy_vf_switcher_config: "{{ vf_switcher_rendered_config }}"

- name: Copy vf-switcher configuration to artifacts
  copy:
    src: "{{ deploy_vf_switcher_config }}"
    dest: "{{ artifacts }}/vf-switcher.yaml"

# Note(abdallahyas): The /etc/vf-switcher directory must be present
# on the machine and is owned by the user run by the ansible scripts.
# This is done because the vf-switcher handling should be done by admins
# only, to not expose the scripts for non admin users.

- name: Copy vf-switcher configuration to /etc/vf-switcher
  copy:
    src: "{{ deploy_vf_switcher_config }}"
    dest: "/etc/vf-switcher/vf-switcher.yaml"

- name: Deploy Kind cluster {{ project }}
  command:
    cmd: sudo systemctl restart vf-switcher

